const cannot be updated or re-declared
Uncaught SyntaxError c:\Users\BM\novice\introduction and basics\VarLetConst.js:58
const salimia = "say habari gani instead"
      ^

SyntaxError: Identifier 'salimia' has already been declared